Repository applied-ml-bde/bde, pull requests merged in 2024-09, with the labels that each got.

#26 Update README.md
  README.md
Labels: bug, documentation

#25 6 multi network training
  bde/ml/datasets.py
  bde/ml/models.py
  pyproject.toml
  tests/conftest.py
  tests/pytest.ini
  tests/test_ml/test_datasets/test_dataset_wrapper.py
  tests/test_ml/test_models/test_bde_estimator.py
  tests/test_ml/test_models/test_estimators_general.py
  tests/test_ml/test_models/test_fully_connected_estimator.py
Labels: enhancement

#28 Repo config files
  .gitattributes
  .github/ISSUE_TEMPLATE/dev.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/lint.yml
  .github/workflows/python-app.yml
  .github/workflows/testing.yml
  .gitignore
  .pre-commit-config.yaml
  LICENSE
  README.md
  bde/__init__.py
  bde/ml/__init__.py
  bde/ml/datasets.py
  bde/ml/loss.py
  bde/ml/models.py
  bde/ml/training.py
  bde/utils/__init__.py
  bde/utils/configs.py
  bde/utils/utils.py
  doc/Makefile
  pixi.lock
  pyproject.toml
  tests/test_ml/test_models/test_estimators_general.py
Labels: bug, enhancement
