Repository applied-ml-bde/bde, pull requests merged in 2024-10, with the labels that each got.

#36 Read me project overview
  README.md
Labels: documentation

#37 Apidoc documentation
  .github/workflows/deploy-gh-pages.yml
  .pre-commit-config.yaml
  README.md
  doc/Makefile
  doc/_static/css/project-template.css
  doc/_static/img/index_api.svg
  doc/_static/img/index_examples.svg
  doc/_static/img/index_getting_started.svg
  doc/_static/img/index_user_guide.svg
  doc/_static/img/logo.png
  doc/_static/img/logo.psd
  doc/_static/img/logo.svg
  doc/_static/js/copybutton.js
  doc/api.md
  doc/conf.py
  doc/index.rst
  doc/make.bat
  doc/source/bde.ml.rst
  doc/source/bde.rst
  doc/source/bde.utils.rst
  examples/README.txt
  pyproject.toml
Labels: documentation, enhancement

#39 Update README.md
  README.md
Labels: documentation

#31 11 implement mcmc stage
  .github/workflows/python-app.yml
  README.md
  bde/ml/datasets.py
  bde/ml/loss.py
  bde/ml/models.py
  bde/ml/training.py
  bde/utils/utils.py
  pixi.lock
  pyproject.toml
  requirements.txt
  tests/test_ml/test_loss/test_log_likelihood_loss.py
  tests/test_ml/test_models/test_bde_estimator.py
  tests/test_ml/test_models/test_estimators_general.py
  tests/test_ml/test_models/test_fully_connected_estimator.py
  tests/test_ml/test_training/test_jitted_training.py
Labels: enhancement

#40 Update index.rst
  .gitignore
  bde/__init__.py
  doc/conf.py
  doc/index.rst
  pixi.lock
  pyproject.toml
Labels: documentation

#35 Steffen jw licensefile
  LICENSE
Labels: enhancement

#42 Examples
  .pre-commit-config.yaml
  README.md
  bde/ml/datasets.py
  bde/ml/models.py
  examples/example01.py
  pixi.lock
Labels: bug, documentation

#43 Doc update idx
  LICENSE
  doc/index.rst
  pyproject.toml
Labels: documentation

#44 Documentation
  .pre-commit-config.yaml
  bde/utils/discovery.py
  doc/_templates/class.rst
  doc/_templates/function.rst
  doc/_templates/numpydoc_docstring.py
  doc/_templates/sidebar-search-bs.html
  doc/api.rst
  doc/quick_start.rst
  doc/user_guide.rst
  pixi.lock
  pyproject.toml
Labels: documentation

#45 Update api.rst
  doc/api.md
  doc/api.rst
Labels: documentation

#46 Update index.rst
  doc/index.rst
Labels: documentation

#47 Update user_guide.rst
  doc/user_guide.rst
Labels: documentation
